package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Emisor emisor;
     private Municipios municipios;
     private String rfcCliente;
     private String nombreRazonSocial;
     private String direccion;
     private String cp;
     private String telefono;
     private String correo;
     private char estatus;
     private Date fechaModificacion;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(Emisor emisor, Municipios municipios, String rfcCliente, String nombreRazonSocial, String direccion, String cp, String telefono, char estatus, Date fechaModificacion) {
        this.emisor = emisor;
        this.municipios = municipios;
        this.rfcCliente = rfcCliente;
        this.nombreRazonSocial = nombreRazonSocial;
        this.direccion = direccion;
        this.cp = cp;
        this.telefono = telefono;
        this.estatus = estatus;
        this.fechaModificacion = fechaModificacion;
    }
    public Cliente(Emisor emisor, Municipios municipios, String rfcCliente, String nombreRazonSocial, String direccion, String cp, String telefono, String correo, char estatus, Date fechaModificacion, Set<Factura> facturas) {
       this.emisor = emisor;
       this.municipios = municipios;
       this.rfcCliente = rfcCliente;
       this.nombreRazonSocial = nombreRazonSocial;
       this.direccion = direccion;
       this.cp = cp;
       this.telefono = telefono;
       this.correo = correo;
       this.estatus = estatus;
       this.fechaModificacion = fechaModificacion;
       this.facturas = facturas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Emisor getEmisor() {
        return this.emisor;
    }
    
    public void setEmisor(Emisor emisor) {
        this.emisor = emisor;
    }
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    public String getRfcCliente() {
        return this.rfcCliente;
    }
    
    public void setRfcCliente(String rfcCliente) {
        this.rfcCliente = rfcCliente;
    }
    public String getNombreRazonSocial() {
        return this.nombreRazonSocial;
    }
    
    public void setNombreRazonSocial(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public char getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(char estatus) {
        this.estatus = estatus;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


