package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private DetalleFacturaId id;
     private Iva iva;
     private Factura factura;
     private ConceptoEmisor conceptoEmisor;
     private BigDecimal cantidad;

    public DetalleFactura() {
    }

    public DetalleFactura(DetalleFacturaId id, Iva iva, Factura factura, ConceptoEmisor conceptoEmisor, BigDecimal cantidad) {
       this.id = id;
       this.iva = iva;
       this.factura = factura;
       this.conceptoEmisor = conceptoEmisor;
       this.cantidad = cantidad;
    }
   
    public DetalleFacturaId getId() {
        return this.id;
    }
    
    public void setId(DetalleFacturaId id) {
        this.id = id;
    }
    public Iva getIva() {
        return this.iva;
    }
    
    public void setIva(Iva iva) {
        this.iva = iva;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public ConceptoEmisor getConceptoEmisor() {
        return this.conceptoEmisor;
    }
    
    public void setConceptoEmisor(ConceptoEmisor conceptoEmisor) {
        this.conceptoEmisor = conceptoEmisor;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


