package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private Integer idEstado;
     private String nombre;
     private Set<Municipios> municipioses = new HashSet<Municipios>(0);

    public Estados() {
    }

	
    public Estados(String nombre) {
        this.nombre = nombre;
    }
    public Estados(String nombre, Set<Municipios> municipioses) {
       this.nombre = nombre;
       this.municipioses = municipioses;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Municipios> getMunicipioses() {
        return this.municipioses;
    }
    
    public void setMunicipioses(Set<Municipios> municipioses) {
        this.municipioses = municipioses;
    }




}


