package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private Lote lote;
     private Municipios municipios;
     private InformacionFiscal informacionFiscal;
     private int folio;
     private String serie;
     private Date fechaExpedicion;
     private BigDecimal iva;
     private BigDecimal total;
     private int plantilla;
     private char estatus;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
    }

	
    public Factura(Cliente cliente, Lote lote, Municipios municipios, InformacionFiscal informacionFiscal, int folio, String serie, Date fechaExpedicion, BigDecimal iva, BigDecimal total, int plantilla, char estatus) {
        this.cliente = cliente;
        this.lote = lote;
        this.municipios = municipios;
        this.informacionFiscal = informacionFiscal;
        this.folio = folio;
        this.serie = serie;
        this.fechaExpedicion = fechaExpedicion;
        this.iva = iva;
        this.total = total;
        this.plantilla = plantilla;
        this.estatus = estatus;
    }
    public Factura(Cliente cliente, Lote lote, Municipios municipios, InformacionFiscal informacionFiscal, int folio, String serie, Date fechaExpedicion, BigDecimal iva, BigDecimal total, int plantilla, char estatus, Set<DetalleFactura> detalleFacturas) {
       this.cliente = cliente;
       this.lote = lote;
       this.municipios = municipios;
       this.informacionFiscal = informacionFiscal;
       this.folio = folio;
       this.serie = serie;
       this.fechaExpedicion = fechaExpedicion;
       this.iva = iva;
       this.total = total;
       this.plantilla = plantilla;
       this.estatus = estatus;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Lote getLote() {
        return this.lote;
    }
    
    public void setLote(Lote lote) {
        this.lote = lote;
    }
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    public InformacionFiscal getInformacionFiscal() {
        return this.informacionFiscal;
    }
    
    public void setInformacionFiscal(InformacionFiscal informacionFiscal) {
        this.informacionFiscal = informacionFiscal;
    }
    public int getFolio() {
        return this.folio;
    }
    
    public void setFolio(int folio) {
        this.folio = folio;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public int getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(int plantilla) {
        this.plantilla = plantilla;
    }
    public char getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(char estatus) {
        this.estatus = estatus;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


