package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private Integer idIva;
     private String descripcion;
     private BigDecimal valor;
     private char estatus;
     private char fronterizo;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Iva() {
    }

	
    public Iva(String descripcion, BigDecimal valor, char estatus, char fronterizo) {
        this.descripcion = descripcion;
        this.valor = valor;
        this.estatus = estatus;
        this.fronterizo = fronterizo;
    }
    public Iva(String descripcion, BigDecimal valor, char estatus, char fronterizo, Set<DetalleFactura> detalleFacturas) {
       this.descripcion = descripcion;
       this.valor = valor;
       this.estatus = estatus;
       this.fronterizo = fronterizo;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getIdIva() {
        return this.idIva;
    }
    
    public void setIdIva(Integer idIva) {
        this.idIva = idIva;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public char getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(char estatus) {
        this.estatus = estatus;
    }
    public char getFronterizo() {
        return this.fronterizo;
    }
    
    public void setFronterizo(char fronterizo) {
        this.fronterizo = fronterizo;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


