package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private Integer idLote;
     private Emisor emisor;
     private int folioInicial;
     private int folioFinal;
     private int folioSiguiente;
     private Date fechaAprobacion;
     private Date fechaVigencia;
     private String serieLote;
     private char estatus;
     private String numeroAprobacion;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Lote() {
    }

	
    public Lote(Emisor emisor, int folioInicial, int folioFinal, int folioSiguiente, Date fechaAprobacion, Date fechaVigencia, String serieLote, char estatus, String numeroAprobacion) {
        this.emisor = emisor;
        this.folioInicial = folioInicial;
        this.folioFinal = folioFinal;
        this.folioSiguiente = folioSiguiente;
        this.fechaAprobacion = fechaAprobacion;
        this.fechaVigencia = fechaVigencia;
        this.serieLote = serieLote;
        this.estatus = estatus;
        this.numeroAprobacion = numeroAprobacion;
    }
    public Lote(Emisor emisor, int folioInicial, int folioFinal, int folioSiguiente, Date fechaAprobacion, Date fechaVigencia, String serieLote, char estatus, String numeroAprobacion, Set<Factura> facturas) {
       this.emisor = emisor;
       this.folioInicial = folioInicial;
       this.folioFinal = folioFinal;
       this.folioSiguiente = folioSiguiente;
       this.fechaAprobacion = fechaAprobacion;
       this.fechaVigencia = fechaVigencia;
       this.serieLote = serieLote;
       this.estatus = estatus;
       this.numeroAprobacion = numeroAprobacion;
       this.facturas = facturas;
    }
   
    public Integer getIdLote() {
        return this.idLote;
    }
    
    public void setIdLote(Integer idLote) {
        this.idLote = idLote;
    }
    public Emisor getEmisor() {
        return this.emisor;
    }
    
    public void setEmisor(Emisor emisor) {
        this.emisor = emisor;
    }
    public int getFolioInicial() {
        return this.folioInicial;
    }
    
    public void setFolioInicial(int folioInicial) {
        this.folioInicial = folioInicial;
    }
    public int getFolioFinal() {
        return this.folioFinal;
    }
    
    public void setFolioFinal(int folioFinal) {
        this.folioFinal = folioFinal;
    }
    public int getFolioSiguiente() {
        return this.folioSiguiente;
    }
    
    public void setFolioSiguiente(int folioSiguiente) {
        this.folioSiguiente = folioSiguiente;
    }
    public Date getFechaAprobacion() {
        return this.fechaAprobacion;
    }
    
    public void setFechaAprobacion(Date fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }
    public Date getFechaVigencia() {
        return this.fechaVigencia;
    }
    
    public void setFechaVigencia(Date fechaVigencia) {
        this.fechaVigencia = fechaVigencia;
    }
    public String getSerieLote() {
        return this.serieLote;
    }
    
    public void setSerieLote(String serieLote) {
        this.serieLote = serieLote;
    }
    public char getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(char estatus) {
        this.estatus = estatus;
    }
    public String getNumeroAprobacion() {
        return this.numeroAprobacion;
    }
    
    public void setNumeroAprobacion(String numeroAprobacion) {
        this.numeroAprobacion = numeroAprobacion;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


