package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA



/**
 * MunicipiosId generated by hbm2java
 */
public class MunicipiosId  implements java.io.Serializable {


     private int idMunicipio;
     private int estadosIdEstado;

    public MunicipiosId() {
    }

    public MunicipiosId(int idMunicipio, int estadosIdEstado) {
       this.idMunicipio = idMunicipio;
       this.estadosIdEstado = estadosIdEstado;
    }
   
    public String getIdMunicipio() {
        return new Integer(idMunicipio).toString();
    }
    
    public void setIdMunicipio(String idMunicipio) {
        this.idMunicipio = new Integer(idMunicipio);
    }
    public String getEstadosIdEstado() {
        return new Integer(estadosIdEstado).toString();
    }
    
    public void setEstadosIdEstado(String estadosIdEstado) {
        this.estadosIdEstado = new Integer(estadosIdEstado);
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MunicipiosId) ) return false;
		 MunicipiosId castOther = ( MunicipiosId ) other; 
         
		 return (this.getIdMunicipio()==castOther.getIdMunicipio())
 && (this.getEstadosIdEstado()==castOther.getEstadosIdEstado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + new Integer(this.getIdMunicipio());
         result = 37 * result + new Integer(this.getEstadosIdEstado());
         return result;
   }   


}


