package com.islla.factelect.domain;
// Generated Nov 14, 2012 5:48:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private short id;
     private String descripcion;
     private String abreviatura;
     private Set<ConceptoEmisor> conceptoEmisors = new HashSet<ConceptoEmisor>(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(short id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public UnidadMedida(short id, String descripcion, String abreviatura, Set<ConceptoEmisor> conceptoEmisors) {
       this.id = id;
       this.descripcion = descripcion;
       this.abreviatura = abreviatura;
       this.conceptoEmisors = conceptoEmisors;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public Set<ConceptoEmisor> getConceptoEmisors() {
        return this.conceptoEmisors;
    }
    
    public void setConceptoEmisors(Set<ConceptoEmisor> conceptoEmisors) {
        this.conceptoEmisors = conceptoEmisors;
    }




}


